/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Terraform Wars API
 * REST API for Terraform Wars application.<br><br>Authentication is managed by Django Allauth in headless mode. Open API specification is available <a href='http://localhost:8080/_allauth/openapi.html' target='_blank'>here</a>.<br><br><a href='/admin' class='btn'>Administration</a>
 * OpenAPI spec version: 0.0.1
 */
import type { UserDetailSchemaFirstName } from './userDetailSchemaFirstName';
import type { UserDetailSchemaLastName } from './userDetailSchemaLastName';

export interface UserDetailSchema {
    id: string;
    email: string;
    first_name: UserDetailSchemaFirstName;
    last_name: UserDetailSchemaLastName;
    full_name: string;
    permissions: string[];
}
